replicaCount: 1

image:
  # Published image locations include:
  # - harbor.internal.promethix.net/promethix/cloudflare-tunnel-operator:<tag>
  # - ghcr.io/gentoorax/cloudflare-tunnel-operator:<tag>
  repository: promethix/cloudflare-tunnel-operator
  tag: latest
  pullPolicy: IfNotPresent

namespaceOverride: edge-system

serviceAccount:
  create: true
  name: ""

cloudflare:
  existingSecretName: cloudflare-tunnel-operator
  apiTokenKey: CLOUDFLARE_API_TOKEN
  accountIdKey: CLOUDFLARE_ACCOUNT_ID
  tunnelIdKey: CLOUDFLARE_TUNNEL_ID

operator:
  managedClassName: public
  managedTunnelName: delta-public
  managedIngressClassName: traefik-cloudflare-tunnel
  ingressTargetUrl: https://traefik-cloudflare-tunnel.edge-system.svc.cluster.local
  managedFinalizerName: edge.promethix.net/tunnelpublichostname-protection
  ownershipTag: promethix-cloudflare-tunnel-operator
  ownershipConfigMapNamespace: edge-system
  ownershipConfigMapName: promethix-cloudflare-tunnel-operator-ownership
  applyChanges: false
  reconciliationIntervalSeconds: 30

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
