apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-operator
  namespace: cloudflare-tunnel-operator-system
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: replace-me
  CLOUDFLARE_ACCOUNT_ID: replace-me
  CLOUDFLARE_TUNNEL_ID: replace-me
